#!/bin/bash 
#alineamiento pre-trimming 
raw_data=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut
output_trimmed=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/resultados_cutadapt
ensamble=/home/stephanie/Desktop/TESIS/Ensamble/Ensamble
ALINEAMIENTO=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/ALINEAMIENTO_BOWTIE
ADAPTS=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/resultados_cutadapt
fastqc=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/RESULTADOS_QC_2_TRIMMED
base_name_d1= NGS14-B660_smarter2_nextera_CGTACTAG_L006_R1_001_subset.fastq
base_name_d2= NGS14-B705_P_Q_AGGCAGAA_L004_R1_001_subset.fastq
base_name_d3= NGS14-B706_R_S_GGACTCCT_L004_R1_001_subset.fastq
base_name_d4= NGS14-B707_T_TAGGCATG_L004_R1_001_subset.fastq
base_name_d5= NGS14-B807_W_GGACTCCT_L007_R1_001_subset.fastq
base_name_d6= NGS14-B808_G_TCCTGAGC_L008_R1_001_subset.fastq
bowtie2-build -f $ensamble/Ensamble.fasta  ensamble
#bowtie_d1
bowtie2 -x ensamble -U $raw_data/$base_name_d1 -S $alineamiento/$base_name_d1"_pre.sam" 2> $alineamiento/$base_name_d1"_pre.report"
#bowtie_d3
bowtie2 -x ensamble -U $raw_data/$base_name_d3  -S $alineamiento/$base_name_d3"_pre.sam" 2> $alineamiento/$base_name_d3"_pre.report"
#bowtie_d5
bowtie2 -x ensamble -U $raw_data/$base_name_d5  -S $alineamiento/$base_name_d5"_pre.sam" 2> $alineamiento/$base_name_d5"_pre.report"
#alineamiento post-trimming 
base_name_d1= NGS14-B660_smarter2_nextera_CGTACTAG_L006_R1_001_trimmed.fastq
base_name_d2= NGS14-B705_P_Q_AGGCAGAA_L004_R1_001_ trimmed.fastq base_name_d3= NGS14-B706_R_S_GGACTCCT_L004_R1_001_ trimmed.fastq base_name_d4= NGS14-B707_T_TAGGCATG_L004_R1_001_ trimmed.fastq base_name_d5= NGS14-B807_W_GGACTCCT_L007_R1_001_ trimmed.fastq base_name_d6= NGS14-B808_G_TCCTGAGC_L008_R1_001_ trimmed.fastq
raw_data=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut
output_trimmed=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/resultados_cutadapt
ensamble=/home/stephanie/Desktop/TESIS/Ensamble/Ensamble
ALINEAMIENTO=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/ALINEAMIENTO_BOWTIE
ADAPTS=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/resultados_cutadapt
fastqc=/home/stephanie/Desktop/muestras_PAX6/PAX6_mut/RESULTADOS_QC_2_TRIMMED
#d1
bowtie2 -x ensamble -U $output_trimmed/$base_name_d1".gz" -S $alineamiento/$base_name_d1"_post.sam" 2> $alineamiento/$base_name_d1"_trimmed.report"
#d3
bowtie2 -x ensamble -U $output_trimmed/$base_name_d3".gz" -S $alineamiento/$base_name_d3"_post.sam" 2> $alineamiento/$base_name_d3"_trimmed.report"

#d5
bowtie2 -x ensamble -U $output_trimmed/$base_name_d5".gz" -S $alineamiento/$base_name_d5"_post.sam" 2> $alineamiento/$base_name_d5"_trimmed.report"
